# Generated by Django 3.0.8 on 2020-09-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
