# Generated by Django 3.0.8 on 2020-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
