# Generated by Django 3.0.8 on 2020-10-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201001_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/media'),
        ),
    ]
