# Generated by Django 3.0.8 on 2020-10-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201001_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(default='media/No-image-available.png', null=True, upload_to=''),
        ),
    ]
